# Generated by Django 3.0.4 on 2020-08-13 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('refrence_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('mobile_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('img1', models.BinaryField()),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
