# Generated by Django 3.0.4 on 2020-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='img1',
        ),
        migrations.AddField(
            model_name='appointment',
            name='img',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
