# Generated by Django 3.0.4 on 2020-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200813_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='img',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
