# Generated by Django 2.2.14 on 2020-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200813_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='img',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
