# Generated by Django 2.2.14 on 2020-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200813_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('otp', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'phone_auth',
            },
        ),
    ]
